[project]
name = "langgraph-agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yaduvanshi1998", email = "yadavchandan214@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.3",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.11",
]

[project.scripts]
langgraph-agentic-ai = "langgraph_agentic_ai:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
